-- KyuriAgents tool and MCP governance schema for PostgreSQL 15+.
-- These tables store tool audit logs, policy metadata, and MCP server
-- configuration references. Secrets are intentionally not stored here.

CREATE OR REPLACE FUNCTION agent_tools_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS agent_tool_calls (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id VARCHAR(128) NOT NULL DEFAULT '',
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    thread_id VARCHAR(128),
    tool_name VARCHAR(256) NOT NULL,
    source VARCHAR(16) NOT NULL
        CHECK (source IN ('builtin', 'native', 'mcp', 'runtime')),
    risk VARCHAR(16) NOT NULL
        CHECK (risk IN ('read_only', 'external_read', 'write', 'destructive', 'network')),
    status VARCHAR(16) NOT NULL
        CHECK (status IN ('success', 'error', 'blocked')),
    input_summary TEXT NOT NULL DEFAULT '',
    output_summary TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    error TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_tenant_time
    ON agent_tool_calls (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_call_id
    ON agent_tool_calls (call_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_user_time
    ON agent_tool_calls (tenant_id, user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_thread
    ON agent_tool_calls (tenant_id, thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_tool
    ON agent_tool_calls (tenant_id, tool_name, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_risk
    ON agent_tool_calls (tenant_id, risk, status, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_tool_policies (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    tool_name VARCHAR(256),
    source VARCHAR(16)
        CHECK (source IS NULL OR source IN ('builtin', 'native', 'mcp', 'runtime')),
    risk VARCHAR(16)
        CHECK (risk IS NULL OR risk IN ('read_only', 'external_read', 'write', 'destructive', 'network')),
    effect VARCHAR(16) NOT NULL
        CHECK (effect IN ('allow', 'deny', 'confirm')),
    reason TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_agent_tool_policy
        UNIQUE (tenant_id, user_id, tool_name, source, risk, effect)
);

CREATE INDEX IF NOT EXISTS idx_agent_tool_policies_scope
    ON agent_tool_policies (tenant_id, user_id, effect);
CREATE INDEX IF NOT EXISTS idx_agent_tool_policies_tool
    ON agent_tool_policies (tenant_id, tool_name, effect);

CREATE TABLE IF NOT EXISTS agent_mcp_servers (
    server_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(256) NOT NULL DEFAULT '',
    transport VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    default_risk VARCHAR(16) NOT NULL DEFAULT 'external_read'
        CHECK (default_risk IN ('read_only', 'external_read', 'write', 'destructive', 'network')),
    config_ref TEXT NOT NULL DEFAULT '',
    secret_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_mcp_servers_tenant
    ON agent_mcp_servers (tenant_id, enabled);

DROP TRIGGER IF EXISTS trg_agent_tool_policies_updated_at ON agent_tool_policies;
CREATE TRIGGER trg_agent_tool_policies_updated_at
    BEFORE UPDATE ON agent_tool_policies
    FOR EACH ROW EXECUTE FUNCTION agent_tools_touch_updated_at();

DROP TRIGGER IF EXISTS trg_agent_mcp_servers_updated_at ON agent_mcp_servers;
CREATE TRIGGER trg_agent_mcp_servers_updated_at
    BEFORE UPDATE ON agent_mcp_servers
    FOR EACH ROW EXECUTE FUNCTION agent_tools_touch_updated_at();
