-- KyuriAgents dynamic memory schema for PostgreSQL 15+.
-- LangGraph checkpoint/store tables are managed by LangGraph's own setup.
-- These tables hold product-level memory metadata, audit events, access rules,
-- links, and session summaries owned by KyuriAgents.

CREATE OR REPLACE FUNCTION agent_memory_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS agent_memory_items (
    memory_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    scope_type VARCHAR(16) NOT NULL
        CHECK (scope_type IN ('user', 'project', 'team', 'global')),
    scope_id VARCHAR(128) NOT NULL,
    memory_type VARCHAR(32) NOT NULL
        CHECK (memory_type IN ('preference', 'fact', 'rule', 'decision', 'workflow', 'correction', 'summary')),
    content TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    confidence NUMERIC(5,4) NOT NULL DEFAULT 1.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    importance NUMERIC(5,4) NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    status VARCHAR(16) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'superseded', 'deleted')),
    visibility VARCHAR(16) NOT NULL DEFAULT 'private'
        CHECK (visibility IN ('private', 'team', 'public')),
    source_thread_id VARCHAR(128),
    source_message_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding_model VARCHAR(128) NOT NULL DEFAULT '',
    embedding_version VARCHAR(64) NOT NULL DEFAULT '',
    schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_items_scope
    ON agent_memory_items (tenant_id, scope_type, scope_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_user
    ON agent_memory_items (tenant_id, user_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_type
    ON agent_memory_items (tenant_id, memory_type, status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_visibility
    ON agent_memory_items (tenant_id, visibility, status);
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_expires
    ON agent_memory_items (expires_at)
    WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_tags
    ON agent_memory_items USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_agent_memory_items_source_thread
    ON agent_memory_items (tenant_id, source_thread_id);

CREATE TABLE IF NOT EXISTS agent_memory_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR(128) REFERENCES agent_memory_items (memory_id),
    tenant_id VARCHAR(64) NOT NULL,
    actor_user_id VARCHAR(64),
    event_type VARCHAR(32) NOT NULL
        CHECK (event_type IN ('extracted', 'created', 'updated', 'superseded', 'deleted', 'searched', 'injected')),
    source_thread_id VARCHAR(128),
    source_message_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    before_content TEXT,
    after_content TEXT,
    confidence NUMERIC(5,4)
        CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_events_memory
    ON agent_memory_events (memory_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_events_tenant_type
    ON agent_memory_events (tenant_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_events_thread
    ON agent_memory_events (tenant_id, source_thread_id, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_memory_links (
    tenant_id VARCHAR(64) NOT NULL,
    parent_memory_id VARCHAR(128) NOT NULL REFERENCES agent_memory_items (memory_id),
    child_memory_id VARCHAR(128) NOT NULL REFERENCES agent_memory_items (memory_id),
    link_type VARCHAR(32) NOT NULL
        CHECK (link_type IN ('supports', 'supersedes', 'conflicts', 'derived_from', 'duplicates')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (parent_memory_id, child_memory_id, link_type)
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_links_child
    ON agent_memory_links (child_memory_id, link_type);
CREATE INDEX IF NOT EXISTS idx_agent_memory_links_tenant
    ON agent_memory_links (tenant_id, link_type);

CREATE TABLE IF NOT EXISTS agent_memory_access_rules (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    scope_type VARCHAR(16) NOT NULL
        CHECK (scope_type IN ('user', 'project', 'team', 'global')),
    scope_id VARCHAR(128) NOT NULL,
    subject_type VARCHAR(16) NOT NULL
        CHECK (subject_type IN ('user', 'group', 'tenant')),
    subject_id VARCHAR(128) NOT NULL,
    permission VARCHAR(16) NOT NULL DEFAULT 'read'
        CHECK (permission IN ('read', 'write', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_agent_memory_access_rule
        UNIQUE (tenant_id, scope_type, scope_id, subject_type, subject_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_access_subject
    ON agent_memory_access_rules (tenant_id, subject_type, subject_id);

CREATE TABLE IF NOT EXISTS agent_session_summaries (
    summary_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    thread_id VARCHAR(128) NOT NULL,
    summary TEXT NOT NULL,
    message_start_index INTEGER NOT NULL CHECK (message_start_index >= 0),
    message_end_index INTEGER NOT NULL CHECK (message_end_index >= message_start_index),
    token_count INTEGER CHECK (token_count IS NULL OR token_count >= 0),
    status VARCHAR(16) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'superseded', 'deleted')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_session_summaries_thread
    ON agent_session_summaries (tenant_id, thread_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_session_summaries_user
    ON agent_session_summaries (tenant_id, user_id, status);

DROP TRIGGER IF EXISTS trg_agent_memory_items_updated_at ON agent_memory_items;
CREATE TRIGGER trg_agent_memory_items_updated_at
    BEFORE UPDATE ON agent_memory_items
    FOR EACH ROW EXECUTE FUNCTION agent_memory_touch_updated_at();

DROP TRIGGER IF EXISTS trg_agent_session_summaries_updated_at ON agent_session_summaries;
CREATE TRIGGER trg_agent_session_summaries_updated_at
    BEFORE UPDATE ON agent_session_summaries
    FOR EACH ROW EXECUTE FUNCTION agent_memory_touch_updated_at();
